# Generated by Django 5.2.12 on 2026-03-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_alter_supportticket_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.client'),
        ),
    ]
